driver:
  name: hyperv
  parent_vhd_folder: C:\src\hyperv\WIN2012r2WMF5
  parent_vhd_name: WIN2012r2_WMF5.vhd
  boot_iso_path: C:\src\kitchens\TestScript\Unattendxml.iso
  #iso_path: C:\src\kitchens\TestScript\other.iso
  memory_startup_bytes: 1073741824
  vm_switch: NAT
  ip_address: 10.111.111.117
  subnet: 255.255.255.0
  gateway: 10.111.111.1
  dns_servers: ['8.8.8.8']
transport:
  name: winrm
  username: Administrator
  password: P@ssw0rd

provisioner:
    name: dsc
    dsc_local_configuration_manager_version: wmf5
    dsc_local_configuration_manager:
      reboot_if_needed: true
      configuration_mode_frequency_mins: 15
      debug_mode: none
    configuration_script_folder: examples
    configuration_script: dsc_configuration.ps1
    modules_path: modules
    retry_on_exit_code:
    - 35
    configuration_data_variable: configData
    modules_from_gallery:
     - xPSDesiredStateConfiguration
     - PackageManagementProviderResource

verifier:
  name: pester
  test_folder: ./tests/integration/

platforms:
  - name: win2012r2_Jenkins
    os_type: windows
    shell: powershell

suites:
  - name: JenkinsSvcJavaOption
    driver:
      ip_address: 10.111.111.118
    provisioner:
      configuration_script: JenkinsSvcJavaOption.ps1